---
title: "Developing Data Products - Course Project"
author: "Melissa Sacevich"
date: "7/25/2020"
output: ioslides_presentation
---

## Introduction
This presentation is part of the Course Project for the Coursera Developing Data Products class. The peer assessed assignment has two parts. First, we need to create a Shiny application and deploy it on Rstudio's servers. Second, we should use Slidify or Rstudio Presenter to prepare a reproducible pitch presentation about the application.

## Data Description
The shiny application is based off of the built in R package 'Diamonds'. The dataset contains the prices and other attributes of almost 54,000 diamonds.

* price: price in US dollars ($326–$18,823)
* carat: weight of the diamond (0.2–5.01)
* cut: quality of the cut (Fair, Good, Very Good, Premium, Ideal)
* color: diamond colour, from J (worst) to D (best)
* clarity: a measurement of how clear the diamond is (I1 (worst), SI1, SI2, VS1, VS2, VVS1, VVS2, IF (best))
* x: length in mm (0--10.74)
* y: width in mm (0--58.9)
* z: depth in mm (0--31.8)
* depth: total depth percentage = z / mean(x, y) = 2 * z / (x + y) (43--79)
* table: width of top of diamond relative to widest point (43--95)

## Instructions
This interactive application allows the user to explore diamond prices based on relevant variables (e.g. cut, color, clarity, etc.). 

* First the user must select the sample size using the slide bar

* Then the user may select the variables of interest using the X-axis and Y-axis drop downs

* Finally the user may select a varibale for the measure color

## Shiny Application and Data
The app is available at: https://msacevich.shinyapps.io/Diamonds/

ui.R and server.R files are available on the GitHub: https://github.com/msacevich/Developing-Data-Products---Course-Project 
